# Generated by Django 2.2.1 on 2021-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='soon_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True)),
                ('categori', models.CharField(max_length=20)),
                ('score', models.FloatField(max_length=20)),
                ('tell', models.CharField(max_length=20)),
                ('restaurant', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('sig_menu', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('menu', models.CharField(max_length=250)),
                ('lat', models.FloatField(max_length=20)),
                ('long', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tourlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True)),
                ('restaurant', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('lat', models.FloatField(max_length=20)),
                ('long', models.FloatField(max_length=20)),
            ],
        ),
    ]
