# Generated by Django 2.2.1 on 2021-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soonfood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='select_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=20)),
            ],
        ),
    ]
