# Generated by Django 2.2.1 on 2021-10-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soonfood_app', '0002_select_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='select_food',
            new_name='check_select_food',
        ),
    ]
